import { SOURCE_REPOSITORY, SOURCE_BRANCH_URL } from './source-config.mjs';

declare const __WEB_SOURCE_REVISION__: string;

export const WEB_SOURCE_REVISION = typeof __WEB_SOURCE_REVISION__ === 'string' ? __WEB_SOURCE_REVISION__ : '';
export const WEB_SOURCE_BRANCH = SOURCE_BRANCH_URL;
export const WEB_SOURCE_URL = WEB_SOURCE_REVISION
  ? `${SOURCE_REPOSITORY}/tree/${WEB_SOURCE_REVISION}`
  : WEB_SOURCE_BRANCH;
export const WEB_SOURCE_ARCHIVE = WEB_SOURCE_REVISION
  ? `${SOURCE_REPOSITORY}/archive/${WEB_SOURCE_REVISION}.zip`
  : null;
